SELECT * FROM BOOKS;
SELECT CATEGORY AS "CatDesc" FROM BOOKS;

CREATE TABLE CATEGORY AS (SELECT CATEGORY AS "CatDesc" FROM BOOKS);
ALTER TABLE CATEGORY 
MODIFY ("CatDesc" VARCHAR2(10));
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

--2
CREATE TABLE EMPLOYEES (
Emp# NUMBER (5),
Lastname VARCHAR2(10),
Firstname VARCHAR2(10),
Job_class VARCHAR2(4));

ALTER TABLE EMPLOYEES
ADD (EMPDATE DATE DEFAULT SYSDATE,
ENDDATE DATE);

ALTER TABLE EMPLOYEES
MODIFY (JOB_CLASS CHAR (2));

ALTER TABLE EMPLOYEES
DROP COLUMN ENDDATE;

RENAME EMPLOYEES 
TO JL_EMPS;

SELECT * FROM JL_EMPS;
DESC JL_EMPS;

SELECT ISBN "ID",COST,RETAIL,CATEGORY FROM BOOKS;

CREATE TABLE BOOK_PRICING AS(
SELECT ISBN "ID",COST,RETAIL,CATEGORY FROM BOOKS
);

ALTER TABLE BOOK_PRICING
SET UNUSED(CATEGORY);

TRUNCATE TABLE BOOK_PRICING;

DROP TABLE BOOK_PRICING PURGE;

FLASHBACK TABLE
JL_EMPS
TO BEFORE DROP;

DROP TABLE
JL_EMPS;


SELECT * FROM BOOK_PRICING;

CREATE TABLE store_reps
(rep_ID  NUMBER(5)CONSTRAINT storereps_repID_pk PRIMARY KEY,
last VARCHAR2(15),
first VARCHAR2(10),
comm CHAR(1) DEFAULT 'Y' );

ALTER TABLE STORE_REPS
MODIFY first NOT NULL;

ALTER TABLE STORE_REPS
MODIFY last NOT NULL;

ALTER TABLE STORE_REPS
MODIFY COMM CHECK (COMM IN('Y','N'));

ALTER TABLE STORE_REPS
ADD (BASE_SALARY NUMBER(7,2));

ALTER TABLE STORE_REPS
MODIFY base_salary CONSTRAINT storereps_basesalary_c CHECK(BASE_SALARY>0);

CREATE TABLE BOOK_STORES (
STORE_ID NUMBER(8) CONSTRAINT BOOKSTORES_STOREID_PK PRIMARY KEY,
NAME VARCHAR2(30),
CONTACT VARCHAR2(30),
REP_ID NUMBER(5),
FOREIGN KEY (REP_ID) REFERENCES STORE_REPS (REP_ID));

ALTER TABLE BOOK_STORES
MODIFY NAME CONSTRAINT BOOKSTORES_NAME_N NOT NULL;

ALTER TABLE BOOK_STORES
MODIFY NAME CONSTRAINT BOOKSTORES_NAME_U UNIQUE;

ALTER TABLE BOOK_STORES
DROP CONSTRAINT SYS_C001619955;

ALTER TABLE BOOK_STORES
ADD CONSTRAINT BOOKSTORES_REPID_FK FOREIGN KEY (REP_ID) REFERENCES STORE_REPS (REP_ID) ON DELETE CASCADE;



CREATE TABLE REP_CONTRACTS (
Store_ID NUMBER(8),
NAME NUMBER (5),
QUARTER CHAR(3),
REP_ID NUMBER(5),
PRIMARY KEY (REP_ID,STORE_ID,QUARTER),
FOREIGN KEY (STORE_ID) REFERENCES BOOK_STORES (STORE_ID),
FOREIGN KEY (REP_ID) REFERENCES STORE_REPS (REP_ID)
);

select * from user_constraints where table_name='BOOK_STORES';

ALTER TABLE STORE_REPS
DISABLE CONSTRAINT STOREREPS_BASESALARY_C;

ALTER TABLE STORE_REPS
ENABLE CONSTRAINT STOREREPS_BASESALARY_C;


INSERT INTO STORE_REPS (rep_ID,last,first,comm,base_salary) VALUES (2,'cabrera','jose','Y',100.533);

truncate table store_reps;
desc store_reps;
select * from store_reps;
SELECT * FROM rep_contracts;
SELECT * FROM BOOK_STORES;
SELECT * FROM user_constraints;