--2.2
SELECT TITLE,COST,RETAIL, ROUND(((RETAIL-COST)/COST)*100,2)
AS "PROFIT %" FROM BOOKS;

SELECT * FROM BOOKS;

--3.1
CREATE TABLE ROOMRESERVATION(
RESERVATION_ID NUMBER(4) CONSTRAINT RR_RESERVATIONID_PK PRIMARY KEY,
ROOM_TYPE VARCHAR2(20),
GUEST_EMAIL VARCHAR2(25) CONSTRAINT RR_RESERVATIONID_NN NOT NULL,
BOOKING_DATE DATE,
ARRIVAL_DATE DATE,
DEPARTURE_DATE DATE,
NUM_GUESTS NUMBER(4),
SPECIAL_REQUESTS VARCHAR2(50));


DESC ROOMRESERVATION;
select * from user_constraints where table_name='ROOMRESERVATION';

--2.2
INSERT INTO ROOMRESERVATION(RESERVATION_ID, GUEST_EMAIL,ROOM_TYPE)
VALUES (10,'cabrerajuel28@gmail.com','TWIN');

INSERT INTO ROOMRESERVATION(RESERVATION_ID, GUEST_EMAIL,ROOM_TYPE)
VALUES (11,'cabrera28@gmail.com','KING');

SELECT * FROM ROOMRESERVATION;

